apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
spec:
  ports:
  - port: 80
    targetPort: {{ .Values.port }}
    protocol: TCP
    name: backend-port
  selector:
    app: {{ .Values.appName }}
    tier: backend
  type: NodePort